# Generated by Django 5.0.6 on 2024-06-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='image',
            new_name='previewImage',
        ),
        migrations.CreateModel(
            name='ShirtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shirt_images/')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.shirt')),
            ],
        ),
    ]
