# Generated by Django 5.0.6 on 2024-06-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
