# Generated by Django 5.0.6 on 2024-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='M', max_length=100),
        ),
    ]
