# Generated by Django 5.0.6 on 2024-06-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
    ]
