# Generated by Django 5.0.6 on 2024-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_address_near_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='near_address',
            field=models.TextField(default='xxxx'),
        ),
    ]
