# Generated by Django 5.0.6 on 2024-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_address_near_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='near_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
