# Generated by Django 5.0.6 on 2024-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_address_near_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='near_address',
            field=models.CharField(default='default_near_address', max_length=3000),
        ),
    ]
