# Generated by Django 5.0.6 on 2024-06-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_address_near_address'),
    ]

    operations = [
    ]
