# Generated by Django 5.0.6 on 2024-06-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_set_default_near_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='near_address',
        ),
    ]
